chooseCRANmirror(31,graphics=F)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = TRUE)
install.packages('https://cran.r-project.org/src/contrib/Archive/foreign/foreign_0.8-71.tar.gz',repos=NULL,type='source')
devtools::install_github('dustinfife/fifer')
install.packages('https://cran.r-project.org/src/contrib/Archive/future/future_1.8.1.tar.gz', repos=NULL, type='source') 
install.packages('networkD3')
install.packages('stringi')    
install.packages('https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.3.2.tar.gz', repos=NULL, type='source')
install.packages("lsa")
install.packages("plot3D")
install.packages("gtools")
install.packages("LiblineaR")
install.packages("SparseM")
